title: Astrology Arith(m)etic
description: Structured astrological knowledge archive
baseurl: "/Astro-Arith-Archive" # the subpath of your site, e.g. /blog
url: "https://example.github.io" # the base hostname & protocol for your site
markdown: kramdown
plugins:
  - jekyll-feed
